site_name: Notes Pot
theme:
  name: material
  palette:
    # -- colors setting --
    # palettle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: switch to dark mode
      primary: cyan
      accent: cyan

    # palettle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: switch to light mode
      primary: cyan
      accent: cyan

  # -- font settings --
  font:
    text: Inter
    code: JetBrainsMono Nerd Font

  # -- language settings --
  language: en

  # -- features --
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.tabs.link
    - content.tooltips
    - header.autohide
    - announce.dismiss
    - search.highlight
    - search.share
    - search.suggest
    # -- navigation specific
    - navigation.footer
    - navigation.indexes
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

extra_css:
  - css/termynal.css
  - css/custom.css

extra_javascript:
  - js/termynal.js
  - js/custom.js

plugins:
  - offline
  - tags
  - search

markdown_extensions:
  - markdown.extensions.toc:
      slugify:
        !!python/object/apply:pymdownx.slugs.slugify { kwds: { case: lower } }
      permalink: "🔗"
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path:
        - "codes"
      check_paths: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tabbed:
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - sane_lists
  - md_in_html
  - admonition
  - tables
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
